  language: python
  python:
    - "3.6"
  before_install:
    - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
    - tar -xzvf protobuf-2.4.1.tar.gz
    - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
  install:
    - pip install -r requirements.txt
  script:
    - python src/scrape/main.py